### ISSUE TITLE
Extremly slow sync on start

### ISSUE THREAD

**Issue by daking007** [ProjectIxian/Ixian-DLT#2]
Commit 60da4232ae4a6f2ea1391c05f3cc012c46ad1a6f causes extremely slow sync as it has to verify the signatures of the last 20k blocks. Shouldn't it verify only the unconfirmed blocks (max last 1k blocks)?

https://github.com/ProjectIxian/Ixian-DLT/blob/60da4232ae4a6f2ea1391c05f3cc012c46ad1a6f/IxianDLT/Block/BlockSync.cs#L517

Something like this?
`if (Node.blockChain.Count > 16 && b.blockNum > wsSyncConfirmedBlockNum && !Node.blockProcessor.verifyBlockSignatures(b))`

**Comment by ashkante** [comment]
Thanks for the suggestion! Some improvements were already made, but the real step forward in sync times will be the disabling of full history on standard nodes (planned for one of the future releases).
