### ISSUE TITLE
How to run correctly Ixian-DLT as linux service?

### ISSUE THREAD

**Issue by nivanko** [ProjectIxian/Ixian-DLT#4]
Hello!
Currently, I ran Ixian-DLT in the foreground, using screen utility, but I want to run it as service. There are two helpers to do this: mono-service, and mono-service2. Manpage for them says "Use mono-service to run services that use the 1.0 assemblies and use mono-service2 to run services that use the 2.0 assemblies."
So which one can I use?

**Comment by ashkante** [comment]
Hi!

Right at the moment I can't say we support running as a service (it's on our internal ToDo for one of the future releases, along with an option to run Ixian in a Docker container).
The main problem, I think, would be the way Ixian executable uses the console, but I'll look into adding a switch to suppress all console output.

I hven't yet played around with 'mono-service' or 'mono-service2', but I will look into them and how they might be used and what are the prerequisites to make Ixian work as that.
Unfortunately, I can't really promise any schedule for this...

**Comment by nivanko** [comment]
Hi!
AFAIK, for latest Mono release (stable), 'mono-service' and 'mono-service2' are the same, so you may not waste your time comparing them.

**Comment by IxiAngel** [comment]
Hi!

Currently the only way to run Ixian DLT in the background is by using screen, tmux or similar software.
