### ISSUE TITLE
Using the sdk to develop new functions and applications and create coins inside the blockchain

### ISSUE THREAD

**Issue by Spoiledpay** [ProjectIxian/Ixian-DLT#9]
Dear,

the possibility of new functionalities related to private blockchain and examples of configuration, creation of coins or internal tokens. And C# app examples. 
thanks.

**Comment by firestorm40** [comment]
At the moment the SDK is still in development, but you can refer to projects such as Spixi, LiteWallet or IxianMiner for examples on how to integrate and use the Ixian blockchain. Setting up a private blockchain is possible, but requires some additional steps compared to deploying a normal IxianDLT node. A guide showing how to setup a private blockchain is in the works as well.
